INSERT INTO countries (name, alfasitwo, alfasithree, isocode) VALUES
('Afganistán', 'AF', 'AFG', '4'),
('Albania', 'AL', 'ALB', '8'),
('Alemania', 'DE', 'DEU', '276'),
('Andorra', 'AD', 'AND', '20'),
('Angola', 'AO', 'AGO', '24'),
('Anguilla', 'AI', 'AIA', '660'),
('Antártida', 'AQ', 'ATA', '10'),
('Antigua y Barbuda', 'AG', 'ATG', '28'),
('Arabia Saudí', 'SA', 'SAU', '682'),
('Argelia', 'DZ', 'DZA', '12'),
('Argentina', 'AR', 'ARG', '32'),
('Armenia', 'AM', 'ARM', '51'),
('Aruba', 'AW', 'ABW', '533'),
('Australia', 'AU', 'AUS', '36'),
('Austria', 'AT', 'AUT', '40'),
('Azerbaiyán', 'AZ', 'AZE', '31'),
('Bahamas', 'BS', 'BHS', '44'),
('Bangladés', 'BD', 'BGD', '50'),
('Barbados', 'BB', 'BRB', '52'),
('Baréin', 'BH', 'BHR', '48'),
('Belgica', 'BE', 'BEL', '56'),
('Belice', 'BZ', 'BLZ', '84'),
('Benin', 'BJ', 'BEN', '204'),
('Bermudas', 'BM', 'BMU', '60'),
('Bielorussia', 'BY', 'BLR', '112'),
('Birmania', 'MM', 'MMR', '104'),
('Bolivia', 'BO', 'BOL', '68'),
('Bosnia y Herzegovina', 'BA', 'BIH', '70'),
('Botsuana', 'BW', 'BWA', '72'),
('Brasil', 'BR', 'BRA', '76'),
('Brunéi', 'BN', 'BRN', '96'),
('Bulgaria', 'BG', 'BGR', '100'),
('Burkina Faso', 'BF', 'BFA', '854'),
('Burundi', 'BI', 'BDI', '108'),
('Bután', 'BT', 'BTN', '64'),
('Cabo Verde', 'CV', 'CPV', '132'),
('Camboya', 'KH', 'KHM', '116'),
('Camerún', 'CM', 'CMR', '120'),
('Canadá', 'CA', 'CAN', '124'),
('Caribe Neerlandés', 'BQ', 'BES', '535'),
('Catar', 'QA', 'QAT', '634'),
('Chad', 'TD', 'TCD', '148'),
('Chile', 'CL', 'CHL', '152'),
('China', 'CN', 'CHN', '156'),
('Chipre', 'CY', 'CYP', '196'),
('Colombia', 'CO', 'COL', '170'),
('Comoras', 'KM', 'COM', '174'),
('Corea del Norte', 'KP', 'PRK', '408'),
('Corea del Sur', 'KR', 'KOR', '410'),
('Costa de Marfil', 'CI', 'CIV', '384'),
('Costa Rica', 'CR', 'CRI', '188'),
('Croacia', 'HR', 'HRV', '191'),
('Cuba', 'CU', 'CUB', '192'),
('Curazao', 'CW', 'CUW', '531'),
('Dinamarca', 'DK', 'DNK', '208'),
('Dominica', 'DM', 'DMA', '212'),
('Ecuador', 'EC', 'ECU', '218'),
('Egipto', 'EG', 'EGY', '818'),
('El Salvador', 'SV', 'SLV', '222'),
('Emiratos árabes Unidos', 'AE', 'ARE', '784'),
('Eritrea', 'ER', 'ERI', '232'),
('Eslovaquia', 'SK', 'SVK', '703'),
('Eslovenia', 'SI', 'SVN', '705'),
('España', 'ES', 'ESP', '724'),
('Estados Federados de Micronesia', 'FM', 'FSM', '583'),
('Estados Unidos', 'US', 'USA', '840'),
('Estonia', 'EE', 'EST', '233'),
('Etiopía', 'ET', 'ETH', '231'),
('Filipinas', 'PH', 'PHL', '608'),
('Finlandia', 'FI', 'FIN', '246'),
('Fiyi', 'FJ', 'FJI', '242'),
('Francia', 'FR', 'FRA', '250'),
('Gabon', 'GA', 'GAB', '266'),
('Gambia', 'GM', 'GMB', '270'),
('Georgia', 'GE', 'GEO', '268'),
('Ghana', 'GH', 'GHA', '288'),
('Gibraltar', 'GI', 'GIB', '292'),
('Granada', 'GD', 'GRD', '308'),
('Grecia', 'GR', 'GRC', '300'),
('Groenlandia', 'GL', 'GRL', '304'),
('Guadelupe', 'GP', 'GLP', '312'),
('Guam', 'GU', 'GUM', '316'),
('Guatemala', 'GT', 'GTM', '320'),
('Guayana Francesa', 'GF', 'GUF', '254'),
('Guernsey', 'GG', 'GGY', '831'),
('Guinea', 'GN', 'GIN', '324'),
('Guinea Ecuatorial', 'GQ', 'GNQ', '226'),
('Guinea-Bissau', 'GW', 'GNB', '624'),
('Guyana', 'GY', 'GUY', '328'),
('Haití', 'HT', 'HTI', '332'),
('Honduras', 'HN', 'HND', '340'),
('Hong Kong', 'HK', 'HKG', '344'),
('Hungría', 'HU', 'HUN', '348'),
('Iceland', 'IS', 'ISL', '352'),
('India', 'IN', 'IND', '356'),
('Indonesia', 'ID', 'IDN', '360'),
('Irak', 'IQ', 'IRQ', '368'),
('Iran', 'IR', 'IRN', '364'),
('Isla de Man', 'IM', 'IMN', '833'),
('Isla de Navidad', 'CX', 'CXR', '162'),
('Isla Norfolk', 'NF', 'NFK', '574'),
('Islandia', 'IE', 'IRL', '372'),
('Islas Caimán', 'KY', 'CYM', '136'),
('Islas Cocos', 'CC', 'CCK', '166'),
('Islas Cook', 'CK', 'COK', '184'),
('Islas Feroe', 'FO', 'FRO', '234'),
('Islas Georgias y Sandwich del Sur', 'GS', 'SGS', '239'),
('Islas Malvinas', 'FK', 'FLK', '238'),
('Islas Marianas del Norte', 'MP', 'MNP', '580'),
('Islas Marshall', 'MH', 'MHL', '584'),
('Islas Pitcairn', 'PN', 'PCN', '612'),
('Islas Salomón', 'SB', 'SLB', '90'),
('Islas Turcas y Caicos', 'TC', 'TCA', '796'),
('Islas Vírgenes Británicas', 'VG', 'VGB', '92'),
('Islas Vírgenes de los Estados Unidos', 'VI', 'VIR', '850'),
('Israel', 'IL', 'ISR', '376'),
('Italia', 'IT', 'ITA', '380'),
('Jamaica', 'JM', 'JAM', '388'),
('Japón', 'JP', 'JPN', '392'),
('Jersey', 'JE', 'JEY', '832'),
('Jordania', 'JO', 'JOR', '400'),
('Kazajistán', 'KZ', 'KAZ', '398'),
('Kenia', 'KE', 'KEN', '404'),
('Kirguistán', 'KG', 'KGZ', '417'),
('Kiribati', 'KI', 'KIR', '296'),
('Kosovo', 'XK', 'XKX', '153'),
('Kuweit', 'KW', 'KWT', '414'),
('Laos', 'LA', 'LAO', '418'),
('Lesoto', 'LS', 'LSO', '426'),
('Letonia', 'LV', 'LVA', '428'),
('Libano', 'LB', 'LBN', '422'),
('Liberia', 'LR', 'LBR', '430'),
('Libia', 'LY', 'LBY', '434'),
('Liechtenstein', 'LI', 'LIE', '438'),
('Lituania', 'LT', 'LTU', '440'),
('Luxemburgo', 'LU', 'LUX', '442'),
('Macao', 'MO', 'MAC', '446'),
('Macedonia', 'MK', 'MKD', '807'),
('Madagascar', 'MG', 'MDG', '450'),
('Malasia', 'MY', 'MYS', '458'),
('Malaui', 'MW', 'MWI', '454'),
('Maldivas', 'MV', 'MDV', '462'),
('Mali', 'ML', 'MLI', '466'),
('Malta', 'MT', 'MLT', '470'),
('Marruecos', 'MA', 'MAR', '504'),
('Martinica', 'MQ', 'MTQ', '474'),
('Mauricio', 'MU', 'MUS', '480'),
('Mauritania', 'MR', 'MRT', '478'),
('Mayotte', 'YT', 'MYT', '175'),
('México', 'MX', 'MEX', '484'),
('Moldavia', 'MD', 'MDA', '498'),
('Monaco', 'MC', 'MCO', '492'),
('Mongolia', 'MN', 'MNG', '496'),
('Monténégro', 'ME', 'MNE', '499'),
('Montserrat', 'MS', 'MSR', '500'),
('Mozambique', 'MZ', 'MOZ', '508'),
('Namibia', 'NA', 'NAM', '516'),
('Nauru', 'NR', 'NRU', '520'),
('Nepal', 'NP', 'NPL', '524'),
('Nicaragua', 'NI', 'NIC', '558'),
('Niger', 'NE', 'NER', '562'),
('Nigeria', 'NG', 'NGA', '566'),
('Niue', 'NU', 'NIU', '570'),
('Noruega', 'NO', 'NOR', '578'),
('Nueva Caledonia', 'NC', 'NCL', '540'),
('Nueva Zelanda', 'NZ', 'NZL', '554'),
('Omán', 'OM', 'OMN', '512'),
('Países Bajos', 'NL', 'NLD', '528'),
('Pakistán', 'PK', 'PAK', '586'),
('Palaos', 'PW', 'PLW', '585'),
('Palestina', 'PS', 'PSE', '275'),
('Panama', 'PA', 'PAN', '591'),
('Papúa Nueva Guinea', 'PG', 'PNG', '598'),
('Paraguay', 'PY', 'PRY', '600'),
('Perú', 'PE', 'PER', '604'),
('Polinesia Francesa', 'PF', 'PYF', '258'),
('Polonia', 'PL', 'POL', '616'),
('Portugal', 'PT', 'PRT', '620'),
('Puerto Rico', 'PR', 'PRI', '630'),
('Reino Unido', 'GB', 'GBR', '826'),
('República árabe Saharaui DemocrÁtica', 'EH', 'ESH', '732'),
('República Centroafricana', 'CF', 'CAF', '140'),
('República Checa', 'CZ', 'CZE', '203'),
('República del Congo', 'CG', 'COG', '178'),
('República DemocrÁtica del Congo', 'CD', 'COD', '180'),
('República Dominicana', 'DO', 'DOM', '214'),
('Reunión', 'RE', 'REU', '638'),
('Ruanda', 'RW', 'RWA', '646'),
('Rumania', 'RO', 'ROU', '642'),
('Rusia', 'RU', 'RUS', '643'),
('Samoa', 'WS', 'WSM', '882'),
('Samoa Americana', 'AS', 'ASM', '16'),
('San Bartolomé', 'BL', 'BLM', '652'),
('San Cristóbal y Nieves', 'KN', 'KNA', '659'),
('San Marino', 'SM', 'SMR', '674'),
('San Martín', 'MF', 'MAF', '534'),
('San Pedro y Miquelón', 'PM', 'SPM', '666'),
('San Vicente y las Granadinas', 'VC', 'VCT', '670'),
('Santa Lucía', 'LC', 'LCA', '662'),
('Santo Tomé y Príncipe', 'ST', 'STP', '678'),
('Senegal', 'SN', 'SEN', '686'),
('Serbia', 'RS', 'SRB', '688'),
('Seychelles', 'SC', 'SYC', '690'),
('Sierra Leona', 'SL', 'SLE', '694'),
('Singapur', 'SG', 'SGP', '702'),
('Sint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '654'),
('Sint-Maarten', 'SX', 'SXM', '663'),
('Siria', 'SY', 'SYR', '760'),
('Somalia', 'SO', 'SOM', '706'),
('Sri Lanka', 'LK', 'LKA', '144'),
('eSwatani', 'SZ', 'SWZ', '748'),
('Sudáfrica', 'ZA', 'ZAF', '710'),
('Sudán', 'SD', 'SDN', '729'),
('Sudán del Sur', 'SS', 'SSD', '728'),
('Suecia', 'SE', 'SWE', '752'),
('Suiza', 'CH', 'CHE', '756'),
('Surinam', 'SR', 'SUR', '740'),
('Tailandia', 'TH', 'THA', '764'),
('Taiwan', 'TW', 'TWN', '158'),
('Tanzania', 'TZ', 'TZA', '834'),
('Tayikistán', 'TJ', 'TJK', '762'),
('Territorio Británico del Océano índico', 'IO', 'IOT', '86'),
('Tierras Australes y Antárticas Francesas', 'TF', 'ATF', '260'),
('Timor Oriental', 'TL', 'TLS', '626'),
('Togo', 'TG', 'TGO', '768'),
('Tokelau', 'TK', 'TKL', '772'),
('Tonga', 'TO', 'TON', '776'),
('Trinidad y Tobago', 'TT', 'TTO', '780'),
('Túnez', 'TN', 'TUN', '788'),
('Turkmenistán', 'TM', 'TKM', '795'),
('Turquía', 'TR', 'TUR', '792'),
('Tuvalu', 'TV', 'TUV', '798'),
('Ucrania', 'UA', 'UKR', '804'),
('Uganda', 'UG', 'UGA', '800'),
('Uruguay', 'UY', 'URY', '858'),
('Uzbekistán', 'UZ', 'UZB', '860'),
('Vanuatu', 'VU', 'VUT', '548'),
('Vaticano', 'VA', 'VAT', '336'),
('Venezuela', 'VE', 'VEN', '862'),
('Vietnam', 'VN', 'VNM', '704'),
('Wallis y Futuna', 'WF', 'WLF', '876'),
('Yemen', 'YE', 'YEM', '887'),
('Yibuti', 'DJ', 'DJI', '262'),
('Zambia', 'ZM', 'ZMB', '894'),
('Zimbabwe', 'ZW', 'ZWE', '716'); 




INSERT INTO phone_codes (country_isocode, area_code, full_code, description) VALUES
('170', '6', '57-6', 'Armenia'),
('170', '5', '57-5', 'Barranquilla'),
('170', '1', '57-1', 'Bogotá'),
('170', '7', '57-7', 'Bucaramanga'),
('170', '2', '57-2', 'Cali'),
('170', '5', '57-5', 'Cartagena'),
('170', '7', '57-7', 'Cúcuta'),
('170', '8', '57-8', 'Ibagué'),
('170', '6', '57-6', 'Manizales'),
('170', '4', '57-4', 'Medellín'),
('170', '310', '57-310', 'Mobile Phones - Comcel'),
('170', '311', '57-311', 'Mobile Phones - Comcel'),
('170', '312', '57-312', 'Mobile Phones - Comcel'),
('170', '315', '57-315', 'Mobile Phones - Movistar'),
('170', '316', '57-316', 'Mobile Phones - Movistar'),
('170', '300', '57-300', 'Mobile Phones - Ola'),
('170', '301', '57-301', 'Mobile Phones - Ola'),
('170', '8', '57-8', 'Neiva'),
('170', '2', '57-2', 'Palmira'),
('170', '6', '57-6', 'Pereira'),
('170', '5', '57-5', 'Santa Marta'),
('170', '8', '57-8', 'Villavicencio');


INSERT INTO subdivisioncategories (id, description) VALUES
(1, 'Department'),
(2, 'Capital District'),
(3, 'State'),
(4, 'District'),
(5, 'Outlying Area');


INSERT INTO stateregions (code, name, countrycode, isocode3166, subdivision_id) VALUES
('CO-AMA', 'Amazonas', '170', 'CO-AMA', 1),
('CO-ANT', 'Antioquia', '170', 'CO-ANT', 1),
('CO-ARA', 'Arauca', '170', 'CO-ARA', 1),
('CO-ATL', 'Atlántico', '170', 'CO-ATL', 1),
('CO-BOL', 'Bolívar', '170', 'CO-BOL', 1),
('CO-BOY', 'Boyacá', '170', 'CO-BOY', 1),
('CO-CAL', 'Caldas', '170', 'CO-CAL', 1),
('CO-CAQ', 'Caquetá', '170', 'CO-CAQ', 1),
('CO-CAS', 'Casanare', '170', 'CO-CAS', 1),
('CO-CAU', 'Cauca', '170', 'CO-CAU', 1),
('CO-CES', 'Cesar', '170', 'CO-CES', 1),
('CO-CHO', 'Chocó', '170', 'CO-CHO', 1),
('CO-CUN', 'Cundinamarca', '170', 'CO-CUN', 1),
('CO-COR', 'Córdoba', '170', 'CO-COR', 1),
('CO-DC', 'Distrito Capital de Bogotá', '170', 'CO-DC', 2),
('CO-GUA', 'Guainía', '170', 'CO-GUA', 1),
('CO-GUV', 'Guaviare', '170', 'CO-GUV', 1),
('CO-HUI', 'Huila', '170', 'CO-HUI', 1),
('CO-LAG', 'La Guajira', '170', 'CO-LAG', 1),
('CO-MAG', 'Magdalena', '170', 'CO-MAG', 1),
('CO-MET', 'Meta', '170', 'CO-MET', 1),
('CO-NAR', 'Nariño', '170', 'CO-NAR', 1),
('CO-NSA', 'Norte de Santander', '170', 'CO-NSA', 1),
('CO-PUT', 'Putumayo', '170', 'CO-PUT', 1),
('CO-QUI', 'Quindío', '170', 'CO-QUI', 1),
('CO-RIS', 'Risaralda', '170', 'CO-RIS', 1),
('CO-SAP', 'San Andrés, Providencia y Santa Catalina', '170', 'CO-SAP', 1),
('CO-SAN', 'Santander', '170', 'CO-SAN', 1),
('CO-SUC', 'Sucre', '170', 'CO-SUC', 1),
('CO-TOL', 'Tolima', '170', 'CO-TOL', 1),
('CO-VAC', 'Valle del Cauca', '170', 'CO-VAC', 1),
('CO-VAU', 'Vaupés', '170', 'CO-VAU', 1),
('CO-VID', 'Vichada', '170', 'CO-VID', 1);

-- Insertar subdivisiones de Estados Unidos
INSERT INTO stateregions (code, name, countrycode, isocode3166, subdivision_id) VALUES
('US-AL', 'Alabama', '840', 'US-AL', 3),
('US-AK', 'Alaska', '840', 'US-AK', 3),
('US-AS', 'American Samoa', '840', 'US-AS', 5),
('US-AZ', 'Arizona', '840', 'US-AZ', 3),
('US-AR', 'Arkansas', '840', 'US-AR', 3),
('US-CA', 'California', '840', 'US-CA', 3),
('US-CO', 'Colorado', '840', 'US-CO', 3),
('US-CT', 'Connecticut', '840', 'US-CT', 3),
('US-DE', 'Delaware', '840', 'US-DE', 3),
('US-DC', 'District of Columbia', '840', 'US-DC', 4),
('US-FL', 'Florida', '840', 'US-FL', 3),
('US-GA', 'Georgia', '840', 'US-GA', 3),
('US-GU', 'Guam', '840', 'US-GU', 5),
('US-HI', 'Hawaii', '840', 'US-HI', 3),
('US-ID', 'Idaho', '840', 'US-ID', 3),
('US-IL', 'Illinois', '840', 'US-IL', 3),
('US-IN', 'Indiana', '840', 'US-IN', 3),
('US-IA', 'Iowa', '840', 'US-IA', 3),
('US-KS', 'Kansas', '840', 'US-KS', 3),
('US-KY', 'Kentucky', '840', 'US-KY', 3),
('US-LA', 'Louisiana', '840', 'US-LA', 3),
('US-ME', 'Maine', '840', 'US-ME', 3),
('US-MD', 'Maryland', '840', 'US-MD', 3),
('US-MA', 'Massachusetts', '840', 'US-MA', 3),
('US-MI', 'Michigan', '840', 'US-MI', 3),
('US-MN', 'Minnesota', '840', 'US-MN', 3),
('US-MS', 'Mississippi', '840', 'US-MS', 3),
('US-MO', 'Missouri', '840', 'US-MO', 3),
('US-MT', 'Montana', '840', 'US-MT', 3),
('US-NE', 'Nebraska', '840', 'US-NE', 3),
('US-NV', 'Nevada', '840', 'US-NV', 3),
('US-NH', 'New Hampshire', '840', 'US-NH', 3),
('US-NJ', 'New Jersey', '840', 'US-NJ', 3),
('US-NM', 'New Mexico', '840', 'US-NM', 3),
('US-NY', 'New York', '840', 'US-NY', 3),
('US-NC', 'North Carolina', '840', 'US-NC', 3),
('US-ND', 'North Dakota', '840', 'US-ND', 3),
('US-MP', 'Northern Mariana Islands', '840', 'US-MP', 5),
('US-OH', 'Ohio', '840', 'US-OH', 3),
('US-OK', 'Oklahoma', '840', 'US-OK', 3),
('US-OR', 'Oregon', '840', 'US-OR', 3),
('US-PA', 'Pennsylvania', '840', 'US-PA', 3),
('US-PR', 'Puerto Rico', '840', 'US-PR', 5),
('US-RI', 'Rhode Island', '840', 'US-RI', 3),
('US-SC', 'South Carolina', '840', 'US-SC', 3),
('US-SD', 'South Dakota', '840', 'US-SD', 3),
('US-TN', 'Tennessee', '840', 'US-TN', 3),
('US-TX', 'Texas', '840', 'US-TX', 3),
('US-UM', 'United States Minor Outlying Islands', '840', 'US-UM', 5),
('US-UT', 'Utah', '840', 'US-UT', 3),
('US-VT', 'Vermont', '840', 'US-VT', 3),
('US-VI', 'Virgin Islands, U.S.', '840', 'US-VI', 5),
('US-VA', 'Virginia', '840', 'US-VA', 3),
('US-WA', 'Washington', '840', 'US-WA', 3),
('US-WV', 'West Virginia', '840', 'US-WV', 3),
('US-WI', 'Wisconsin', '840', 'US-WI', 3),
('US-WY', 'Wyoming', '840', 'US-WY', 3);